name 'openssl'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures openssl'
long_description 'Installs/Configures openssl'
version '0.1.0'
